### ISSUE TITLE
Illustrated CSS3 details and cases

### ISSUE THREAD

**Issue by madneal** [neal1991/reading-notes#5]
**Structure pseudo class selector**
* nth-child(n)
* nth-last-child(n)
* nth-of-type(n)
* nth-last-of-type(n)

The n begins with 1 instead of 0. If n is 0, it will not match any element. The n could be integer (1,2,3,4), key word(odd, even), or equation(2n+1, -n+5).
Hence the n could be:
1. specific number
2. equation n*length
3. equation n+length
4. equation -n+length

**The scenes to be used of nth-of-type**
* To format a free style interface, for example the rotation angle of picture
* Make the picture alternately float to left and right
* Make special style for the first paragraph
* Make a alternate style for a list
* Make figure

**Pseudo elements**
* `::first-letter`
* `::first-line`
* `::before` and `::after`
* `::selection`, it can only accepts two attribute, including background and color.

**attribute selector**
* E[attr]
* E[attr=val]
* E[attr|=val]
* E[attr~=val]
* E[attr*=val]
* E[attr^=val]
* E[attr$=val]

**border-radius**
* Set just one value, top-left = top-right = bottom-right = bottom-left
* Set two values: top-left = bottom-right, top-right = bottom-left
* Set three values: the first is top-left, the second are top-right and bottom-left, the third is bottom-right
* Set four values: top-left, top-right, bottom-right, bottom-left

And the border-radius can be set respectively:
* border-top-left-radius
* border-top-right-radius
* border-bottom-right-radius
* border-bottom-left-radius

The attributes of border-radius can contain two values:
The first is the horizontal fillet radius, and the second is the vertical fillet radius. And the two values will be split by '/'.
*NOTICE:*
When set the specific border-radius(e.g. border-top-left-radius), the '/' is not needed. If you add, it will be a wrong behavior.

### [Utilize border-radius to make different shapes](https://codepen.io/nealecnu/pen/oWwzEx?editors=1100#0)

**The basic background attributes:**
* background-color
* background-image
* background-repeat
* background-attachment
* background-position
* background-origin
* background-clip
* background-size
* background-break
 
The conditions to validate the text-overflow:
* width
* white-space:nowrap
* overflow:hidden

> note:word-wrap cannot work in \<pre\> and \<table\>
Punctuation is not allowed placed at the beginning of the line in IE, but allowed in Chrome/Safari/Firefox.

**box model**
1) W3C standard box model
outer box:
element width = content width + padding + border + margin
element height = content height + padding + border + margin
inner box:
element width = content width + padding + border
element height = content height + padding + border
2)IE traditional box model
outer box:
element width = content width + margin
element height = content height + margin
inner box:
element width = content width
element height = content height

### How to tell different versions of Flexbox
* For 'display:box' or 'box-{*}', it is the version in 2009.
* For 'display:flexbox' or 'flex()', it is the version in 2011, called hybrid version either.
* For 'display:flex' or 'flex-{*}', it is the current version, and the standard version of W3C.

**Comment by neal1991** [comment]
** The scenes to be used of nth-of-type**
* To format a free style interface, for example the rotation angle of picture
* Make the picture alternately float to left and right
* Make special style for the first paragraph
* Make a alternate style for a list
* Make figure

**Comment by neal1991** [comment]
**Pseudo elements**
* ::first-letter
* ::firest-line
* ::before and ::after
* ::selection, it can only accepts two attribute, including background and color.

**Comment by neal1991** [comment]
**attribute selector**
* E[attr]
* E[attr=val]
* E[attr|=val]
* E[attr~=val]
* E[attr*=val]
* E[attr^=val]
* E[atttr$=val]

**Comment by neal1991** [comment]
**border-radius**
* Set just one value, top-left = top-right = bottom-right = bottom-left
* Set two values: top-left = bottom-right, top-right = bottom-left
* Set three values: the first is top-left, the second are top-right and bottom-left, the third is bottom-right
* Set four values: top-left, top-right, bottom-right, bottom-left
